### PR TITLE
Feature/add mobx router

### PR DESCRIPTION
**Pull request by florida**
- [x] implement mobX router to navigate between flows
- [x] adds screens for splash and login pages
- [x] setup base app flow (actual logins and user flows not wired up)

### CODE REVIEW

**Comment by mattmallon** [comment]
Awesome! Thank you!

**Comment by mattmallon** [comment]
@florida Unfortunately none of the code from your pull requests is working on my machine. :( I'm getting multiple errors. I spent some time trying to fix the errors I was seeing, but I wasn't able to figure it out. Each time I fixed something, a new error popped up. It looks like some of this stuff might still be a work in progress? For instance, in the splashscreen component, it is importing a NavigationBar from AppWrapper that does not exist. Should NavigationBar be changed to an AppWrapper componentin the appscreen jsx? I had lots of question marks like that, where I wasn't sure what direction you were headed in, so I didn't want to make changes to the code before understanding what you were trying to do. When you've fixed your changes and all of the views are working on your local machine, please make another pull request (it's fine if both of your previous pull requests are compacted down to one) and I can merge it as soon as I can verify that it is working! Thank you! Here are some of the errors I am seeing when I try to visit the base route: 

- In splashscreen: Cannot find module "../components/appWrapper"
- In App.jsx: Cannot resolve 'file' or 'directory' ./components/dashboard
- In appWrapper/index.js: SyntaxError: JSX attributes must only be assigned a non-empty expression (it's pointing to onClick={} in the first button)

I hope that makes sense! Thank you!

**Comment by rapi-castillo** [comment]
I just removed the onClick and it worked for me @mattmallon

**Comment by rapi-castillo** [comment]
Also we were working on the prototype that Tino created! It's posted in the
#project-swimmy room. You need to have flinto in your phone to view it on
your phone, or I can also show it to you via conf! ❤❤

**Comment by mattmallon** [comment]
@florida @rapi-progcode Thanks for the help, Rapi! That was one of the errors, there was also another one I found where there was an outdated reference to the dashboard component (which had been moved) in an import statement. I got it working now. I reverted my reverts (ha!) and then made a new commit that fixed the errors. If you pull from master, you should be good to go.

**Comment by florida** [comment]
@mattmallon @rapi-progcode totally missed this but I hope that y'all have gotten it working! I also have #8 open, there are however a few merge conflicts that needs to be addressed in that PR.

There's also feature/login-and-auth that has a basic auth screen.

I'll go and fix that PR, cheers!

**Pull request merged**
